apiVersion: apps/v1
kind: Deployment
metadata:
  name: personas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personas-service
  template:
    metadata:
      labels:
        app: personas-service
    spec:
      containers:
        - name: personas-service
          image: lerambot/personas-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/seguros_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: Postgres2025
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
